### ISSUE TITLE
The code is not running properly

### ISSUE THREAD

**Issue by flaclimate** [asjolaviral/scopusapi#1]
I think there is an issue at this line:
  
TotalResult = info['search-results']['opensearch:totalResults']

inside the first loop of case_list[]

Apparently, search-results is undefined.

Would you please check if this is the case?

Thanks!
Francesca

**Comment by asjolaviral** [comment]
Hi Francesca,

Thank you for your comment on the code. You were correct about the issue. I've rechecked the API documentation and made the necessary changes to fix the issue. I really appreciate your input.

Best regards,
Viral
